import * as S from "./players.style.js";
import { Link } from 'react-router-dom';
import Button from 'react-bootstrap/Button';

const PlayersData = [
    {
        id: 0,
        photo: "",
        name: "에릭 요키시",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 43",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
        
    ,
    {
        id: 1,
        photo: "",
        name: "문성현",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 39",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 2,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 3,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 4,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 5,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 2,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 2,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 2,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    },
    {
        id: 2,
        photo: "",
        name: "정찬헌",
        age: 34,
        nationality: "USA",
        RL: "Right",
        defenseRatio: 0.7,
        team: "KIWOOM",
        contract: "4년",
        scoutsum: '좋은 영입이 될 것',
        gamec: 5,
        strout: 29,
        winc: 2,
        ops : 123,
        score : 2.27,
        ballf : 3,
        whip : 1.04,
        bastr : 29/3,
        innings : '31 2/3',
        hits : 30,
        ballc : 474,
        homerun : 0,
        injury : '팔, 다리 부상',
        position: "투수",
        number: "No. 22",
        photo: "",
        box: <S.Box></S.Box>,
        profile: 
        <Link to ="./playerss/playersInfo">
            <Button variant="secondary" >자세히 보기</Button>
        </Link>,
    }

]
export default PlayersData;